# Generated by Django 4.2.3 on 2023-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
    ]
